/**
 * PageCraft Example Plugin — Word Counter
 * ────────────────────────────────────────────────────────────────────────────
 * Demonstrates the full Plugin SDK surface:
 *   • lifecycle hooks (builder:init, section:afterAdd, section:afterRemove)
 *   • custom block registration
 *   • toolbar button
 *   • custom CSS injection
 *   • sdk.sections API
 *   • sdk.ui helpers
 *
 * Usage — include after builder.html:
 *   <script src="example-plugin.js"></script>
 *
 * Or load dynamically:
 *   const s = document.createElement('script')
 *   s.src = 'example-plugin.js'
 *   document.head.appendChild(s)
 * ────────────────────────────────────────────────────────────────────────────
 */

;(function () {
  'use strict'

  // ── Guard: wait for PageCraft to be ready ──────────────────────────────────
  if (typeof window.PageCraft === 'undefined') {
    console.error('[WordCounterPlugin] PageCraft not found. Load builder.html first.')
    return
  }

  // ── Plugin descriptor ──────────────────────────────────────────────────────
  window.PageCraft.registerPlugin({
    id:          'word-counter',
    name:        'Word Counter',
    version:     '1.0.0',
    description: 'Shows a live word count for all sections, and adds a Quote block type.',
    author:      'Your Name',

    /**
     * init(sdk) is called once when the plugin is registered.
     * @param {object} sdk — the full Plugin SDK surface
     */
    init(sdk) {

      // ── 1. Inject scoped CSS ─────────────────────────────────────────────
      sdk.addCSS(`
        #wc-badge {
          display: inline-flex;
          align-items: center;
          gap: 5px;
          padding: 4px 10px;
          background: rgba(108,99,255,0.15);
          border: 1px solid rgba(108,99,255,0.3);
          border-radius: 20px;
          font-size: 11px;
          font-weight: 600;
          color: #a78bfa;
          cursor: pointer;
          transition: background .15s;
        }
        #wc-badge:hover { background: rgba(108,99,255,0.25); }
      `)

      // ── 2. Add a word-count button to the topbar ─────────────────────────
      sdk.addToolbarButton('📝 0 words', 'Word count across all sections', () => {
        const count = _countWords(sdk.sections.getAll())
        sdk.ui.toast(`${count.toLocaleString()} words across ${sdk.sections.getAll().length} sections`, '📝')
      })

      // Re-label the button element after it's been created
      function _updateBadge() {
        const btn = document.getElementById('plugin-btn-word-counter')
        if (btn) btn.textContent = `📝 ${_countWords(sdk.sections.getAll()).toLocaleString()} words`
      }

      // ── 3. Register lifecycle hooks ──────────────────────────────────────
      sdk.on('builder:init', () => {
        _updateBadge()
        sdk.ui.toast('Word Counter plugin loaded ✓', '🔌')
      })

      sdk.on('section:afterAdd', ({ section }) => {
        _updateBadge()
        console.log('[WordCounter] section added:', section.type)
      })

      sdk.on('section:afterRemove', ({ id }) => {
        _updateBadge()
        console.log('[WordCounter] section removed:', id)
      })

      // ── 4. Hook into export to append a word-count comment ───────────────
      sdk.on('export:beforeHTML', (payload) => {
        const count = _countWords(sdk.sections.getAll())
        payload.html = payload.html.replace(
          '</body>',
          `<!-- Generated by PageCraft | Word count: ${count} -->\n</body>`
        )
      })

      // ── 5. Register a custom "Quote" block type ──────────────────────────
      sdk.registerBlock(
        {
          type:        'plugin-quote',
          label:       'Quote Block',
          icon:        '❝',
          color:       '#a78bfa22',
          desc:        'Styled pull-quote with attribution',
          props: {
            quote:       'The best way to predict the future is to create it.',
            author:      'Peter Drucker',
            bgColor:     '#0f172a',
            textColor:   '#ffffff',
            accentColor: '#a78bfa',
          },
          schema: [
            { g: 'Content', f: [
              { k: 'quote',  l: 'Quote text',    t: 'textarea' },
              { k: 'author', l: 'Attribution',   t: 'text' },
            ]},
          ],
          styleSchema: [
            { k: 'bgColor',     l: 'Background' },
            { k: 'textColor',   l: 'Text'       },
            { k: 'accentColor', l: 'Accent'     },
          ],
        },
        // renderer(props, sectionId) → HTML string
        (p, id) => `
<section style="background:${_ec(p.bgColor)};color:${_ec(p.textColor)};
  padding:64px clamp(24px,8vw,80px);text-align:center;">
  <div style="max-width:700px;margin:0 auto;">
    <div style="font-size:clamp(2rem,5vw,4rem);color:${_ec(p.accentColor)};
      line-height:1;margin-bottom:12px;font-family:Georgia,serif;">"</div>
    <blockquote
      contenteditable="true"
      data-id="${id}" data-key="quote"
      style="font-size:clamp(1.1rem,2.5vw,1.6rem);font-style:italic;
        line-height:1.6;margin:0 0 24px;"
    >${_esc(p.quote)}</blockquote>
    <cite
      contenteditable="true"
      data-id="${id}" data-key="author"
      style="font-size:14px;font-style:normal;font-weight:700;
        letter-spacing:.08em;text-transform:uppercase;
        color:${_ec(p.accentColor)};opacity:.8;"
    >— ${_esc(p.author)}</cite>
  </div>
</section>`
      )

      // ── 6. Register a command other plugins / the console can call ────────
      sdk.registerCommand('word-counter:count', () => {
        return _countWords(sdk.sections.getAll())
      })
    },

    // Optional: called by unregisterPlugin() for cleanup
    destroy() {
      console.log('[WordCounter] plugin destroyed — cleaning up')
    },
  })

  // ── Helpers (private to this module) ────────────────────────────────────────

  /** Strip HTML tags and count words in all sections' props */
  function _countWords(sections) {
    const text = sections
      .flatMap(s => Object.values(s.props || {}))
      .filter(v => typeof v === 'string')
      .join(' ')
      .replace(/<[^>]*>/g, ' ')
    return text.trim().split(/\s+/).filter(Boolean).length
  }

  /** Escape HTML entities (mirrors the builder's `e()` helper) */
  function _esc(str) {
    return String(str ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
  }

  /** Escape CSS color value (mirrors the builder's `ec()` helper) */
  function _ec(v) {
    return String(v ?? '').replace(/[^#a-zA-Z0-9(),%. ]/g, '')
  }

})()
